# Generated by Django 6.0.4 on 2026-04-27 08:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredibilityCache',
            fields=[
                ('url', models.URLField(max_length=2048, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('signals_json', models.JSONField()),
                ('scored_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Credibility cache entries',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=63, unique=True)),
                ('topic_label', models.CharField(default='New Research', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_summary', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.session')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['session', 'id'], name='chat_messag_session_f95c7b_idx')],
            },
        ),
    ]
